### ISSUE TITLE
Add docstrings and expand documentation

### ISSUE THREAD

**Issue by sloede** [sloede/SecureArithmetic.jl#10]
Document the basic types such as `SecureVector` or `PlainVector`, including their constructors, and how to use them. Also document auxiliary functions such as `level`, `capacity` etc.

**Comment by sloede** [comment]
@ArseniyKholod it would be great if you could also have a look at this issue over the next few weeks. There is not as much to do as in https://github.com/sloede/OpenFHE.jl/issues/24.

**Comment by ArseniyKholod** [comment]
> Document the basic types such as `SecureVector` or `PlainVector`, including their constructors, and how to use them. Also document auxiliary functions such as `level`, `capacity` etc.

Do I understand correctly that constructors needs to be documented together with corresponding structures inside the same 
"""
doc
"""
? I mean, they have the same names, cross referencing would be problematic...

**Comment by sloede** [comment]
Good question. I don't think so - if they are separate symbols, you can assign a docstring to each, but crossreferncing will not work, agreed.
