### ISSUE TITLE
add user-chosen num_slots in init_bootstrapping! 

### ISSUE THREAD

**Issue by ArseniyKholod** [sloede/SecureArithmetic.jl#17]
https://github.com/sloede/SecureArithmetic.jl/blob/fd6e81253f123d964ec3e4cb5bbe5ec25f38da84/src/openfhe.jl#L38-L39
If one wants to simulate not with whole ciphertext with length of `ring_dim//2`, it have to initialize bootstrapping with own `num_slots`.
I suggest to add one more function `init_bootstrapping! ` with third argument `num_slots`.

@sloede, can I directly create pull requests suggesting features, that are still missing, but needed for simulations?

**Comment by sloede** [comment]
> I suggest to add one more function init_bootstrapping! with third argument num_slots.

Sounds good to me! please note that for now I have chosen the names `capacity` for what OpenFHE calls the `batchSize`, and I use `length` for what OpenFHE calls `num_slots` (at least if I understand correctly).

Thus if you want to add such an additional method, I recommend making the signature something like
```julia
 function init_bootstrapping!(context::SecureContext{<:OpenFHEBackend}, 
                              private_key::PrivateKey, length::Integer) 
```

> can I directly create pull requests suggesting features, that are still missing, but needed for simulations?

Just fork the repo to your personal GitHub account, create a branch in the fork, and then create a PR from the branch in your fork to this repo here. If this does not work, please let me know.
